### ISSUE TITLE
Support local credentials files when installed as package

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/natural-language-classifier-nodejs-cli#1]
We need to get the credentials from a local file or the environment as bluemix is doing.

**Comment by nfriedly** [comment]
We could allow them to be specified as command line arguments or environmental properties. That's what I've done in the past for command line apis that needed credentials.

**Comment by germanattanasio** [comment]
that's a good idea @nfriedly

**Comment by germanattanasio** [comment]
We decided to not go with this project as npm module.
