### ISSUE TITLE
Unable to access web address

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/natural-language-classifier-nodejs-cli#14]
I am trying to access the servicea nd the web address is not recognized  
https://gateway.watsonplatform.net/natural-language-classifier-experimental/api/v1/classifiers/10D41B-nlc-1
(even when replacing experimental by beta)
Can you help ? 
Best regards 
Philippe

**Comment by germanattanasio** [comment]
Hi @PhilippeComte,  

Open a terminal a run:
```
curl -u user:password \
https://gateway.watsonplatform.net/natural-language-classifier-beta/api/v1/classifiers/10D41B-nlc-1
```

If you need credentials you will have to go to Bluemix and create a service in order to get them.
